[green_agent]
agentbeats_id = "019bb369-26ba-73d0-88fd-9e8191212882"
image = "ghcr.io/octuplivia247/agentbeats:latest"
env = {LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "gym_bro"
env = {}

[config]
# Add your assessment config here
