[green_agent]
agentbeats_id = "019bb369-26ba-73d0-88fd-9e8191212882"
env = {LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "purple_agent"
env = {}

[config]
# Add your assessment config here
